Suggested some hints for the Repl
WebAhead/master-reference pull request #8
Opened 2020-03-20 07:49 UTC by jrd656

Add hints to the bottom of the guide, and change the task order to emphasise to read through the guide first.

2020-03-20 08:21 UTC, Karyum commented
@jrd656 should we close the previous pull request then? and want to keep updating this one ?

2020-03-20 08:25 UTC, Karyum requested changes

2020-03-20 08:25 UTC, Karyum commented on coursebook/week-2/dom-manipulation-ws.md
> +    }
using the `toggle` method would be ideal fora situation like this.

```javascript
introductionElement.classList.toggle('highlight')
```

[the toggle method](https://alligator.io/js/classlist/#toggle)

2020-03-20 08:25 UTC, Karyum commented on coursebook/week-2/dom-manipulation-ws.md
> +console.log(1);
i think we can delete these 2 lines from here

2020-03-20 09:49 UTC, jrd656 commented
Yeah I've tried both toggle and add and remove. I was going for add and remove as those were the words used in the question (so I thought it might be steering us to use those methods).

![image](https://user-images.githubusercontent.com/51966598/77152550-dc351780-6aa0-11ea-925c-f65d5d454b8e.png)

I've just tried another method that worked on Moris's computer and I still get the same error.

2020-03-20 10:09 UTC, Karyum commented
@jrd656 hmm ok, it's a different error from the one that was sent in slack, the error also is coming from the tests file (check the second line of the error message) rather than the exercise file.

i've removed it. [click me!](https://repl.it/@Karyum1/DOM-manipulation-Challenge-A)

2020-03-20 10:18 UTC, jrd656 commented
Haha! Wooooooo!!! FINALLY COMPLETED QUESTION 1!!!!!

Cheers mate

2020-03-21 19:15 UTC, Karyum commented
changes moved to #9

2020-03-21 19:15 UTC, closed without merging